exclude:
  - /src/main/java/eu/fasten/vulnerabilityproducer/utils/mappers/YAMLHandler\.java
  - /src/main/java/eu/fasten/vulnerabilityproducer/utils/mappers/JSONHandler\.java
  - /src/main/java/eu/fasten/vulnerabilityproducer/Main\.java
  - /src/main/java/eu/fasten/vulnerabilityproducer/utils/connections/MongoConnector\.java

